name: Docker

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  publish:
    strategy:
      matrix:
        target: ["latest", "exporter"]
    uses: "logicer16/workflows/.github/workflows/docker.yml@main"
    permissions:
      contents: read
      packages: write
    with:
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      tag: ${{ matrix.target }}
      tag-buildarg: IMAGE_TARGET
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  dockerhub-description:
    uses: "logicer16/workflows/.github/workflows/dockerhub-description.yml@main"
    needs:
      - publish
    permissions:
      contents: read
    with:
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
