name: Update Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-repo:
    uses: logicer16/workflows/.github/workflows/update-repo.yml@main
    with:
      upstream: AleixoLucas42/duplicati-prometheus-exporter

  update-docker-image:
    needs: update-repo
    if: ${{ needs.update-repo.outputs.new-commits == 'true' }}
    uses: ./.github/workflows/docker-publish.yaml
    secrets: inherit
